name: Issue and PR comment commands

on:
  issue_comment:
    types: 
      - created
      - edited

permissions:
  issues: write
  pull-requests: write

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
        with:
          egress-policy: audit

      - uses: jpmcb/prow-github-actions@f4d01dd4b13f289014c23fe5a19878a2479cb35b # v1.1.3
        with:
          prow-commands: '/assign 
            /unassign
            /lgtm 
            /milestone'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
