name: helm-test
on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'charts/kyverno/**'
      - '.github/workflows/helm-test.yaml'

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  helm-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@2e205a28d0e1da00c5f53b161f4067b052c61f34
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout
        uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e

      - name: Unshallow
        run: git fetch --prune --unshallow

      - uses: actions/setup-python@7f80679172b057fc5e90d70d197929d454754a5a
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@b0d4458c71155b54fcf33e11dd465dc923550009

      - name: Run chart-testing (lint)
        run: ct lint --target-branch=main --check-version-increment=false
