name: helm-release
on:
  push:
    tags:
      - 'helm-chart-v*'

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  helm-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@2e205a28d0e1da00c5f53b161f4067b052c61f34
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout
        uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e

      - name: Unshallow
        run: git fetch --prune --unshallow

      - uses: actions/setup-python@7f80679172b057fc5e90d70d197929d454754a5a
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@b0d4458c71155b54fcf33e11dd465dc923550009

      - name: Run chart-testing (lint)
        run: ct lint --target-branch=main --check-version-increment=false

  create-release:
    permissions:
      contents: write  # for stefanprodan/helm-gh-pages to push all Helm charts on target dir
    runs-on: ubuntu-latest
    needs: helm-tests
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@2e205a28d0e1da00c5f53b161f4067b052c61f34
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout
        uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e
        with:
          fetch-depth: 0
          
      - name: Install Helm
        uses: azure/setup-helm@18bc76811624f360dbd7f18c2d4ecb32c7b87bab
        with:
          version: v3.4.1

      - name: Run chart-releaser
        uses: stefanprodan/helm-gh-pages@f1701eb82e4d4b82016e7965501c8b6d79feaec9
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          linting: off